#!/bin/bash
#===================================================
#   DESENVOLVIDO POR:   CoutySSH
#===================================================

clear
bash <(wget -qO- raw.githubusercontent.com/CoutySSH/SSH-WEB/main/c12c61c5)
